version: "3"
services:
  tomcat:
    image: tomcat:10.1-jdk11-openjdk-slim
    ports:
      - 8080:8080
    volumes:
      - ./src/main/webapp:/usr/local/tomcat/webapps/ROOT
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    volumes:
      - ./mysql-data:/var/lib/mysql
